export default {
	/** Static icons are retrieved from this URL */
	HOST: "https://raw.githubusercontent.com/victrme/favicon-fetcher/main/package/icons/",

	/** List format is "filename": "urls to match" */
	LIST: {
		/* Do not modify */
		"localhost.svg": ["http://localhost", "localhost:", "http://127.0.0.1:", "127.0.0.1:"],

		/* Can be modified */
		"vscode.png": ["vscode.dev"],
		"microsoft.designer.png": ["designer.microsoft.com"],
		"microsoft.teams.png": ["teams.microsoft.com"],
		"microsoft.outlook.svg": ["outlook.live.com", "outlook.office.com"],
		"microsoft.copilot.svg": ["https://www.bing.com/images/create", "copilot.microsoft.com"],
		"twitter.png": ["twitter.com"],
		"music.google.png": ["music.youtube.com"],
		"youtube.png": ["youtube.com"],
		"instagram.png": ["instagram.com"],
		"whatsapp.svg": ["whatsapp.com"],
		"grok.svg": ["grok.com"],
		"claude.svg": ["claude.ai"],
		"openai.svg": ["chatgpt.com", "openai.com"],
		"discord.svg": ["discord.com"],
		"leboncoin.svg": ["leboncoin.fr"],
		"reddit.png": ["old.reddit.com", "reddit.com"],
		"spotify.svg": ["open.spotify.com", "spotify.com"],
		"google.search.png": ["://google.com", "www.google.com"],
		"google.mail.png": ["mail.google.com", "gmail.com"],
		"google.keep.png": ["keep.google.com"],
		"google.sheets.png": ["docs.google.com/spreadsheets", "sheets.google.com"],
		"google.slides.png": ["docs.google.com/presentation"],
		"google.forms.png": ["docs.google.com/forms"],
		"google.docs.png": ["docs.google.com"],
		"google.maps.png": ["maps.google.com", "google.com/maps"],
		"google.meet.png": ["meet.google.com"],
		"google.chat.png": ["chat.google.com"],
		"google.sites.png": ["sites.google.com"],
		"google.tasks.png": ["tasks.google.com"],
		"google.photos.png": ["photos.google.com"],
		"google.voice.png": ["voice.google.com"],
		"google.calendar.png": ["calendar.google.com"],
		"google.drive.png": ["drive.google.com"],
		"google.messages.png": ["messages.google.com"],
		"google.podcasts.png": ["podcasts.google.com"],
		"google.gemini.svg": ["gemini.google.com"],
		"icloud.mail.png": ["icloud.com/mail/"],
		"amazon.svg": [
			"amazon.com",
			"amazon.ca",
			"amazon.fr",
			"amazon.de",
			"amazon.it",
			"amazon.co.uk",
		],
		"ambank.png": ["amonline.com"],
		"postman.png": ["postman.co"],
		"kagi.png": ["kagi.com"],
		"tiktok.png": ["tiktok.com"],

		/* Captcha protected websites */
		"shopify.png": ["shopify.com"],
		"mangafire.png": ["mangafire.to"],
		"deepseek.png": ["deepseek.com"],
		"coinmarketcap.png": ["coinmarketcap.com"],
		"pixabay.png": ["pixabay.com"],
		"kraken.png": ["kraken.com"],
	} as Record<string, string[]>,
}
