name: Trigger bonjourr-apis update

on:
    push:
        branches:
            - main

jobs:
    trigger:
        runs-on: ubuntu-latest

        steps:
            - name: Send trigger
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.BONJOURR_APIS_ACTIONS }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/victrme/bonjourr-apis/update/dispatches
